<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Typescribe.Domain/Typescribe.Domain.csproj" />
    <ProjectReference Include="../Typescribe.Application/Typescribe.Application.csproj" />
  </ItemGroup>

  <ItemGroup Condition="Exists('tools/typst')">
    <EmbeddedResource Include="tools/typst" LogicalName="Typescribe.Engine.typst" />
  </ItemGroup>

  <ItemGroup Condition="Exists('tools/typst.exe')">
    <EmbeddedResource Include="tools/typst.exe" LogicalName="Typescribe.Engine.typst" />
  </ItemGroup>
</Project>
