<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IsAotCompatible>true</IsAotCompatible>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
    <OptimizationPreference>Speed</OptimizationPreference>
    <StripSymbols>true</StripSymbols>
    <InvariantGlobalization>false</InvariantGlobalization>
    <AssemblyName>Typescribe</AssemblyName>
    <RootNamespace>Typescribe.Desktop</RootNamespace>
    <ApplicationTitle>Typescribe</ApplicationTitle>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="PDFtoImage" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Typescribe.Domain/Typescribe.Domain.csproj" />
    <ProjectReference Include="../Typescribe.Application/Typescribe.Application.csproj" />
    <ProjectReference Include="../Typescribe.Infrastructure/Typescribe.Infrastructure.csproj" />
  </ItemGroup>
</Project>
